services:
  website-blog:
    build: .
    volumes:
      - .:/app
    ports:
      - "59382:3000"
    environment:
      - NODE_ENV=production
      - SITE_API_ORIGIN=${SITE_API_ORIGIN:-http://127.0.0.1:3000}
    restart: always
