import { readdir, readFile, stat, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

import { type ParsedPost, parsePost } from '../lib/blog/parser';

const POSTS_DIR = join(process.cwd(), 'lore/posts');
const OUTPUT_FILE = join(process.cwd(), 'lib/lore/recent-index.generated.ts');

function isValidFilename(filename: string): boolean {
  return /^[a-z0-9][a-z0-9-]*\.md$/i.test(filename);
}

function isValidSlug(value: string): boolean {
  return /^[a-z0-9][a-z0-9-]*$/i.test(value);
}

function normalizeSlug(value: string | undefined): string | null {
  if (!value) return null;
  const trimmed = value.trim().toLowerCase();
  if (!trimmed) return null;
  if (!isValidSlug(trimmed)) return null;
  return trimmed;
}

function parseYYYYMMDDToUtcMs(dateString: string | undefined): number | null {
  if (!dateString) return null;

  const trimmed = dateString.trim();
  const match = trimmed.match(/^(\d{4})-(\d{2})-(\d{2})$/);
  if (!match) return null;

  const year = Number(match[1]);
  const month = Number(match[2]);
  const day = Number(match[3]);

  if (!Number.isFinite(year) || !Number.isFinite(month) || !Number.isFinite(day)) return null;
  if (month < 1 || month > 12) return null;
  if (day < 1 || day > 31) return null;

  const ms = Date.UTC(year, month - 1, day);
  const date = new Date(ms);

  if (date.getUTCFullYear() !== year) return null;
  if (date.getUTCMonth() !== month - 1) return null;
  if (date.getUTCDate() !== day) return null;

  return ms;
}

function getStoryOrderValue(post: ParsedPost): number | null {
  const value = post.metadata.story_order;
  if (typeof value !== 'number' || !Number.isFinite(value)) return null;
  return value;
}

function compareByDisplayDateDesc(a: ParsedPost, b: ParsedPost): number {
  const dateA = parseYYYYMMDDToUtcMs(a.metadata.date);
  const dateB = parseYYYYMMDDToUtcMs(b.metadata.date);

  if (dateA === null && dateB === null) return a.filename.localeCompare(b.filename);
  if (dateA === null) return 1;
  if (dateB === null) return -1;

  if (dateA !== dateB) return dateB - dateA;
  return a.filename.localeCompare(b.filename);
}

function ensureRequiredLoreMetadata(parsed: ParsedPost): boolean {
  const game = normalizeSlug(parsed.metadata.game);
  if (!game) {
    console.error(`Lore post ${parsed.filename} is missing required "game" frontmatter.`);
    return false;
  }

  const storyOrder = getStoryOrderValue(parsed);
  if (storyOrder === null) {
    console.error(
      `Lore post ${parsed.filename} is missing required numeric "story_order" frontmatter.`,
    );
    return false;
  }

  parsed.metadata.game = game;
  parsed.metadata.story_order = storyOrder;
  return true;
}

type IndexedLorePostFile = {
  filename: string;
  explicitPublishDate?: string;
  metadata: {
    title: string;
    summary?: string;
    tags: string[];
    date?: string;
    game: string;
    story_order: number;
  };
};

async function buildLorePostIndex(): Promise<IndexedLorePostFile[]> {
  const files = await readdir(POSTS_DIR);
  const mdFiles = files.filter((filename) => isValidFilename(filename));

  const posts = await Promise.all(
    mdFiles.map(async (filename) => {
      try {
        const filepath = join(POSTS_DIR, filename);
        const content = await readFile(filepath, 'utf-8');
        const parsed = parsePost(filename, content);
        if (!ensureRequiredLoreMetadata(parsed)) {
          return null;
        }

        const explicitPublishDate = parsed.metadata.date;

        if (!parsed.metadata.date) {
          const fileStat = await stat(filepath);
          parsed.metadata.date = fileStat.mtime.toISOString().slice(0, 10);
        }

        return {
          filename,
          parsed,
          explicitPublishDate,
        };
      } catch (error) {
        const errorMessage = error instanceof Error ? error.message : 'Unknown error';
        console.error(`Error indexing ${filename}:`, errorMessage);
        return null;
      }
    }),
  );

  return posts
    .filter(
      (
        post,
      ): post is {
        filename: string;
        parsed: ParsedPost;
        explicitPublishDate: string | undefined;
      } => post !== null,
    )
    .sort((a, b) => compareByDisplayDateDesc(a.parsed, b.parsed))
    .map(({ filename, explicitPublishDate, parsed }) => ({
      filename,
      explicitPublishDate,
      metadata: {
        title: parsed.metadata.title,
        summary: parsed.metadata.summary,
        tags: [...(parsed.metadata.tags ?? [])],
        date: parsed.metadata.date,
        game: parsed.metadata.game ?? '',
        story_order: parsed.metadata.story_order ?? 0,
      },
    }));
}

function renderIndexFile(posts: IndexedLorePostFile[]): string {
  const renderedEntries = JSON.stringify(posts, null, 2);

  return `/**
 * This file is auto-generated by scripts/generate-lore-post-index.ts.
 * Do not edit directly.
 */

export interface IndexedLorePostMetadata {
  title: string;
  summary?: string;
  tags: string[];
  date?: string;
  game: string;
  story_order: number;
}

export interface IndexedLorePostFile {
  filename: string;
  explicitPublishDate?: string;
  metadata: IndexedLorePostMetadata;
}

// biome-ignore format: generated by JSON.stringify with double quotes
export const LORE_POST_FILE_INDEX: IndexedLorePostFile[] = ${renderedEntries};
`;
}

async function main() {
  const posts = await buildLorePostIndex();
  const nextContents = renderIndexFile(posts);

  let currentContents: string | null = null;
  try {
    currentContents = await readFile(OUTPUT_FILE, 'utf-8');
  } catch {
    currentContents = null;
  }

  if (currentContents === nextContents) {
    console.info(`Lore post index is already up to date (${posts.length} entries).`);
    return;
  }

  await writeFile(OUTPUT_FILE, nextContents, 'utf-8');
  console.info(`Wrote lore post index with ${posts.length} entries.`);
}

main().catch((error) => {
  console.error('Failed to generate lore post index:', error);
  process.exit(1);
});
