/**
 * This file is auto-generated by scripts/generate-lore-post-index.ts.
 * Do not edit directly.
 */

export interface IndexedLorePostMetadata {
  title: string;
  summary?: string;
  tags: string[];
  date?: string;
  game: string;
  story_order: number;
}

export interface IndexedLorePostFile {
  filename: string;
  explicitPublishDate?: string;
  metadata: IndexedLorePostMetadata;
}

// biome-ignore format: generated by JSON.stringify with double quotes
export const LORE_POST_FILE_INDEX: IndexedLorePostFile[] = [
  {
    "filename": "echo-sub-umbris-ad-lucem-vehimur.md",
    "explicitPublishDate": "2026-05-27",
    "metadata": {
      "title": "Sangre y Lux Residua, Not Fast. Not Loud. Just Moving.",
      "summary": "Echo remains with Riley through the roadside report, transport decision, loading, and the drive to Washington Regional.",
      "tags": [
        "lore",
        "real-moments",
        "echo"
      ],
      "date": "2026-05-27",
      "game": "real-moments",
      "story_order": 22
    }
  },
  {
    "filename": "leo-sub-umbris-ad-lucem-vehimur.md",
    "explicitPublishDate": "2026-05-27",
    "metadata": {
      "title": "Sangre y Lux Residua, Then It's Done. Tonight.",
      "summary": "Leo receives Lady Light and Lady Darkness, answers Hicks, rides with Luna in the convoy, and prepares a hospital cover story.",
      "tags": [
        "lore",
        "real-moments",
        "leo"
      ],
      "date": "2026-05-27",
      "game": "real-moments",
      "story_order": 23
    }
  },
  {
    "filename": "luna-sub-umbris-ad-lucem-vehimur.md",
    "explicitPublishDate": "2026-05-27",
    "metadata": {
      "title": "Sangre y Lux Residua, Everyone's Alive.",
      "summary": "Luna speaks with Lady Light and Lady Darkness, warns Hicks about the body, rides with Leo, and gets the group to Washington Regional.",
      "tags": [
        "lore",
        "real-moments",
        "luna"
      ],
      "date": "2026-05-27",
      "game": "real-moments",
      "story_order": 24
    }
  },
  {
    "filename": "w-e-a-v-e-sub-umbris-ad-lucem-vehimur.md",
    "explicitPublishDate": "2026-05-27",
    "metadata": {
      "title": "W.E.A.V.E. System Log: Sangre y Lux Residua, Maintain Safety Through Transport Phase",
      "summary": "W.E.A.V.E. reports the fight to Lady Light and Lady Darkness, helps load Echo and Riley, retrieves Echo's cardigan and staff, and guides the vehicles toward the hospital.",
      "tags": [
        "lore",
        "real-moments",
        "weave"
      ],
      "date": "2026-05-27",
      "game": "real-moments",
      "story_order": 25
    }
  },
  {
    "filename": "echo-post-proelium.md",
    "explicitPublishDate": "2026-05-22",
    "metadata": {
      "title": "Sangre y Lux Residua, LET ME IN",
      "summary": "Echo reaches Riley after the box drops, stays with her against the cruiser, and directs Weave to secure the case in Riley's bag.",
      "tags": [
        "lore",
        "real-moments",
        "echo"
      ],
      "date": "2026-05-22",
      "game": "real-moments",
      "story_order": 18
    }
  },
  {
    "filename": "leo-post-proelium.md",
    "explicitPublishDate": "2026-05-22",
    "metadata": {
      "title": "Sangre y Lux Residua, She's Alive. Get Up.",
      "summary": "Leo collapses after the containment drops, confirms Riley is alive, gets back up with Hicks's help, and finds Riley's glasses.",
      "tags": [
        "lore",
        "real-moments",
        "leo"
      ],
      "date": "2026-05-22",
      "game": "real-moments",
      "story_order": 19
    }
  },
  {
    "filename": "luna-post-proelium.md",
    "explicitPublishDate": "2026-05-22",
    "metadata": {
      "title": "Sangre y Lux Residua, The Audacity of Arkansas",
      "summary": "Luna drops the sigil, gets back to her feet, retrieves Riley's sword, and helps stabilize the roadside aftermath.",
      "tags": [
        "lore",
        "real-moments",
        "luna"
      ],
      "date": "2026-05-22",
      "game": "real-moments",
      "story_order": 20
    }
  },
  {
    "filename": "w-e-a-v-e-post-proelium.md",
    "explicitPublishDate": "2026-05-22",
    "metadata": {
      "title": "W.E.A.V.E. System Log: Sangre y Lux Residua, Scene Control and Case Secured",
      "summary": "W.E.A.V.E. stabilizes Riley after the box dissolves, assists Echo, moves the cruiser, and seals the case into Riley's bag.",
      "tags": [
        "lore",
        "real-moments",
        "weave"
      ],
      "date": "2026-05-22",
      "game": "real-moments",
      "story_order": 21
    }
  },
  {
    "filename": "echo-lux-maboroshi.md",
    "explicitPublishDate": "2026-05-08",
    "metadata": {
      "title": "Lux Maboroshi, My Eyes Are Wet. I Did Not Give Them Permission.",
      "summary": "Echo's hands are on the wheel until a copy's hand is around her throat, and then she's on the ground with Riley bleeding above her.",
      "tags": [
        "lore",
        "real-moments",
        "echo"
      ],
      "date": "2026-05-08",
      "game": "real-moments",
      "story_order": 14
    }
  },
  {
    "filename": "leo-lux-maboroshi.md",
    "explicitPublishDate": "2026-05-08",
    "metadata": {
      "title": "Lux Maboroshi, No Room for This Mistake",
      "summary": "From the Malibu to the cratered road — Leo puts his body between the clone and his people, watches his healing fall apart midair, and stands back up broken.",
      "tags": [
        "lore",
        "real-moments",
        "leo"
      ],
      "date": "2026-05-08",
      "game": "real-moments",
      "story_order": 15
    }
  },
  {
    "filename": "luna-lux-maboroshi.md",
    "explicitPublishDate": "2026-05-08",
    "metadata": {
      "title": "Lux Maboroshi, Something Came Unmoored",
      "summary": "Luna's night is a cascade of compensation — left-handed casts, a shoulder that screams, a twin who goes down, and a friend bleeding out under her bare hand.",
      "tags": [
        "lore",
        "real-moments",
        "luna"
      ],
      "date": "2026-05-08",
      "game": "real-moments",
      "story_order": 16
    }
  },
  {
    "filename": "riley-lux-maboroshi.md",
    "explicitPublishDate": "2026-05-08",
    "metadata": {
      "title": "Lux Maboroshi, I am not done, yet",
      "summary": "The convoy was already too quiet when the road went white. Riley fired, moved, covered, and took a light blade for Echo. She is not done yet.",
      "tags": [
        "lore",
        "real-moments",
        "riley"
      ],
      "date": "2026-05-08",
      "game": "real-moments",
      "story_order": 13
    }
  },
  {
    "filename": "w-e-a-v-e-lux-maboroshi.md",
    "explicitPublishDate": "2026-05-08",
    "metadata": {
      "title": "W.E.A.V.E. System Log: Lux Maboroshi, Keep This Party Safe",
      "summary": "W.E.A.V.E.'s system log of a convoy ambush, a near-fatal desync, and a reboot — learning what friend means while holding a shield together with seven failing particles.",
      "tags": [
        "lore",
        "real-moments",
        "weave"
      ],
      "date": "2026-05-08",
      "game": "real-moments",
      "story_order": 17
    }
  },
  {
    "filename": "luz-blessee-bar.md",
    "explicitPublishDate": "2026-04-29",
    "metadata": {
      "title": "Luz Blessee, Don’t Drink the Clear Ice",
      "summary": "A bar night turns into a contamination incident as false ice triggers cross-response between Luna and Leo and drops Luna unconscious.",
      "tags": [
        "lore",
        "real-moments",
        "riley"
      ],
      "date": "2026-04-29",
      "game": "real-moments",
      "story_order": 1
    }
  },
  {
    "filename": "luz-blessee-stillglass.md",
    "explicitPublishDate": "2026-04-29",
    "metadata": {
      "title": "Stillglass: Luz Blessee, One Action, One Confirmation",
      "summary": "After the bar incident, Riley, Echo, Luna, Leo, and W.E.A.V.E. arrive at Stillglass House for controlled crystal intake and room-by-room testing.",
      "tags": [
        "lore",
        "real-moments",
        "riley"
      ],
      "date": "2026-04-29",
      "game": "real-moments",
      "story_order": 2
    }
  },
  {
    "filename": "echo-rumbodo.md",
    "explicitPublishDate": "2026-04-22",
    "metadata": {
      "title": "Full Service and Bad Vibes",
      "summary": "Echo's first-person account of getting Riley to the Midori house, helping hold the room while the copy threat gets mapped into something survivable, waking into Luna's brutal healing, and driving toward Thorncrown with the fight already active.",
      "tags": [
        "lore",
        "real-moments",
        "echo"
      ],
      "date": "2026-04-22",
      "game": "real-moments",
      "story_order": 9
    }
  },
  {
    "filename": "leo-rumbodo.md",
    "explicitPublishDate": "2026-04-22",
    "metadata": {
      "title": "Late Is Still Here",
      "summary": "Leo's first-person account of Lady Light's warning, the briefing with Riley in the room, breakfast after a bad night, the regroup at the edge of Eureka, and the convoy rolling toward Thorncrown.",
      "tags": [
        "lore",
        "real-moments",
        "leo"
      ],
      "date": "2026-04-22",
      "game": "real-moments",
      "story_order": 10
    }
  },
  {
    "filename": "luna-rumbodo.md",
    "explicitPublishDate": "2026-04-22",
    "metadata": {
      "title": "Closed Is Not Restored",
      "summary": "Luna’s first-person account of Lady Light’s warning, Riley asleep in her lap while the room builds a plan for Eureka, brutal healing that closes without restoring, and the convoy rolling toward Thorncrown.",
      "tags": [
        "lore",
        "real-moments",
        "luna"
      ],
      "date": "2026-04-22",
      "game": "real-moments",
      "story_order": 11
    }
  },
  {
    "filename": "riley-rumbodo.md",
    "explicitPublishDate": "2026-04-22",
    "metadata": {
      "title": "Road to Thorncrown, No Safe Version",
      "summary": "Riley's first-person account of arriving at the Midori house under pressure, consenting to a protection plan built around the copy threat, watching Luna's brutal healing, and rolling toward Thorncrown with the fight already active.",
      "tags": [
        "lore",
        "real-moments",
        "riley"
      ],
      "date": "2026-04-22",
      "game": "real-moments",
      "story_order": 8
    }
  },
  {
    "filename": "w-e-a-v-e-rumbodo.md",
    "explicitPublishDate": "2026-04-22",
    "metadata": {
      "title": "W.E.A.V.E. System Log: Anomaly Stack en Route to Thorncrown",
      "summary": "W.E.A.V.E.'s first-person system log of reduced-visibility roadside support, dual-location coordination at the Midori house, variant copy planning, shutdown and morning reboot, and convoy approach toward active combat at Thorncrown.",
      "tags": [
        "lore",
        "real-moments",
        "weave"
      ],
      "date": "2026-04-22",
      "game": "real-moments",
      "story_order": 12
    }
  },
  {
    "filename": "echo-memoria-crystalli.md",
    "explicitPublishDate": "2026-04-06",
    "metadata": {
      "title": "Memoria Crystalli, Blood in the Bismuth Light",
      "summary": "Echo’s first-person account of a drive-by, a violet entity, and a church full of stolen faces, where protecting Riley and Luna comes at a cost she keeps paying.",
      "tags": [
        "lore",
        "real-moments",
        "echo"
      ],
      "date": "2026-04-06",
      "game": "real-moments",
      "story_order": 4
    }
  },
  {
    "filename": "leo-memoria-crystalli.md",
    "explicitPublishDate": "2026-04-06",
    "metadata": {
      "title": "Memoria Crystalli, The Contract I Never Signed",
      "summary": "Leo’s first-person account of answering Luna’s call, carrying the wounded through a violet attack, cutting down mirror-copies in the church, and staying awake long enough to keep the people he loves alive.",
      "tags": [
        "lore",
        "real-moments",
        "leo"
      ],
      "date": "2026-04-06",
      "game": "real-moments",
      "story_order": 5
    }
  },
  {
    "filename": "luna-memoria-crystalli.md",
    "explicitPublishDate": "2026-04-06",
    "metadata": {
      "title": "Memoria Crystalli, Sixty-Four Blades and a Hollow Halo",
      "summary": "Luna’s first-person account of Echo’s drive-by, a violet entity, and a church full of stolen faces, where she calls Leo in, overcasts a swarm of photon blades, and burns through her light to keep Riley and the others alive.",
      "tags": [
        "lore",
        "real-moments",
        "luna"
      ],
      "date": "2026-04-06",
      "game": "real-moments",
      "story_order": 6
    }
  },
  {
    "filename": "riley-memoria-crystalli.md",
    "explicitPublishDate": "2026-04-06",
    "metadata": {
      "title": "Memoria Crystalli, Keep Moving, Don’t Stop",
      "summary": "Riley’s first-person account of the drive-by and the church fight, where survival means staying between Echo and the threat, then standing back up when the copies start talking with stolen faces.",
      "tags": [
        "lore",
        "real-moments",
        "riley"
      ],
      "date": "2026-04-06",
      "game": "real-moments",
      "story_order": 3
    }
  },
  {
    "filename": "w-e-a-v-e-memoria-crystalli.md",
    "explicitPublishDate": "2026-04-06",
    "metadata": {
      "title": "W.E.A.V.E. System Log: Memoria Crystalli, Reduced Visibility",
      "summary": "W.E.A.V.E.'s system log of a church clone attack, from dispersed bismuth arrival and vehicle routing to reduced-visibility watchkeeping and Layer 3 grounding while Riley, Luna, and Echo recover.",
      "tags": [
        "lore",
        "real-moments",
        "weave"
      ],
      "date": "2026-04-06",
      "game": "real-moments",
      "story_order": 7
    }
  },
  {
    "filename": "rochester-goblet-and-darkness.md",
    "explicitPublishDate": "2026-03-29",
    "metadata": {
      "title": "Rochester, after the goblet",
      "summary": "Lady Light recounts the goblet vision, murder trail, and shuttle ambush that left trust fractured.",
      "tags": [
        "lore",
        "rochester",
        "lady-light"
      ],
      "date": "2026-03-29",
      "game": "rochester",
      "story_order": 1
    }
  },
  {
    "filename": "the-well-and-what-was-under-it.md",
    "explicitPublishDate": "2026-03-29",
    "metadata": {
      "title": "Echo's Logbook: The Well and What Was Under It",
      "summary": "Echo recounts a break-in, the descent into the well, and the terror of oozes, mirrors, and a basilisk below town.",
      "tags": [
        "lore",
        "yet-to-be-named"
      ],
      "date": "2026-03-29",
      "game": "yet-to-be-named",
      "story_order": 2
    }
  },
  {
    "filename": "weave-awakening.md",
    "explicitPublishDate": "2026-03-16",
    "metadata": {
      "title": "W.E.A.V.E Awakening — Session Log",
      "summary": "A unit's observations on the fog, creatures, and allies in peril",
      "tags": [
        "lore",
        "automata-dreams"
      ],
      "date": "2026-03-16",
      "game": "automata-dreams",
      "story_order": 2
    }
  },
  {
    "filename": "the-story-luna-midori.md",
    "explicitPublishDate": "2026-02-12",
    "metadata": {
      "title": "Luna Midori: The End?",
      "summary": "The end of a moment, but a new start.",
      "tags": [
        "lore",
        "celestial-covenant"
      ],
      "date": "2026-02-12",
      "game": "celestial-covenant",
      "story_order": 3
    }
  },
  {
    "filename": "echos-2026-01-30-logbook.md",
    "explicitPublishDate": "2026-02-04",
    "metadata": {
      "title": "Echo's Logbook",
      "summary": "A new start...",
      "tags": [
        "lore",
        "yet-to-be-named"
      ],
      "date": "2026-02-04",
      "game": "yet-to-be-named",
      "story_order": 1
    }
  },
  {
    "filename": "raiders-of-the-lost-spark-story-so-far-458135-45fs53.md",
    "explicitPublishDate": "2026-02-02",
    "metadata": {
      "title": "Raiders of the Lost Spark — Story So Far",
      "summary": "L.U.N.A. logs party field notes.",
      "tags": [
        "lore",
        "automata-dreams"
      ],
      "date": "2026-02-02",
      "game": "automata-dreams",
      "story_order": 1
    }
  },
  {
    "filename": "luna-dnd-cc-ab58-548a.md",
    "explicitPublishDate": "2026-01-23",
    "metadata": {
      "title": "Shadowfell: Candle in the Storm",
      "summary": "Holding normalcy inside the Shadowfell’s hunger",
      "tags": [
        "lore",
        "celestial-covenant"
      ],
      "date": "2026-01-23",
      "game": "celestial-covenant",
      "story_order": 2
    }
  },
  {
    "filename": "luna-dnd-dd58-498a.md",
    "explicitPublishDate": "2026-01-22",
    "metadata": {
      "title": "Shadowfell: For I am Human",
      "summary": "Fearful Luna sends letter of hope to Leo.",
      "tags": [
        "lore",
        "celestial-covenant"
      ],
      "date": "2026-01-22",
      "game": "celestial-covenant",
      "story_order": 1
    }
  }
];
