/**
 * This file is auto-generated by scripts/generate-lore-post-index.ts.
 * Do not edit directly.
 */

export interface IndexedLorePostFile {
  filename: string;
  explicitPublishDate?: string;
}

export const LORE_POST_FILE_INDEX: IndexedLorePostFile[] = [
  {
    filename: 'echo-sub-umbris-ad-lucem-vehimur.md',
    explicitPublishDate: '2026-05-27',
  },
  {
    filename: 'leo-sub-umbris-ad-lucem-vehimur.md',
    explicitPublishDate: '2026-05-27',
  },
  {
    filename: 'luna-sub-umbris-ad-lucem-vehimur.md',
    explicitPublishDate: '2026-05-27',
  },
  {
    filename: 'w-e-a-v-e-sub-umbris-ad-lucem-vehimur.md',
    explicitPublishDate: '2026-05-27',
  },
  {
    filename: 'echo-post-proelium.md',
    explicitPublishDate: '2026-05-22',
  },
  {
    filename: 'leo-post-proelium.md',
    explicitPublishDate: '2026-05-22',
  },
  {
    filename: 'luna-post-proelium.md',
    explicitPublishDate: '2026-05-22',
  },
  {
    filename: 'w-e-a-v-e-post-proelium.md',
    explicitPublishDate: '2026-05-22',
  },
  {
    filename: 'echo-lux-maboroshi.md',
    explicitPublishDate: '2026-05-08',
  },
  {
    filename: 'leo-lux-maboroshi.md',
    explicitPublishDate: '2026-05-08',
  },
  {
    filename: 'luna-lux-maboroshi.md',
    explicitPublishDate: '2026-05-08',
  },
  {
    filename: 'riley-lux-maboroshi.md',
    explicitPublishDate: '2026-05-08',
  },
  {
    filename: 'w-e-a-v-e-lux-maboroshi.md',
    explicitPublishDate: '2026-05-08',
  },
  {
    filename: 'luz-blessee-bar.md',
    explicitPublishDate: '2026-04-29',
  },
  {
    filename: 'luz-blessee-stillglass.md',
    explicitPublishDate: '2026-04-29',
  },
  {
    filename: 'echo-rumbodo.md',
    explicitPublishDate: '2026-04-22',
  },
  {
    filename: 'leo-rumbodo.md',
    explicitPublishDate: '2026-04-22',
  },
  {
    filename: 'luna-rumbodo.md',
    explicitPublishDate: '2026-04-22',
  },
  {
    filename: 'riley-rumbodo.md',
    explicitPublishDate: '2026-04-22',
  },
  {
    filename: 'w-e-a-v-e-rumbodo.md',
    explicitPublishDate: '2026-04-22',
  },
  {
    filename: 'echo-memoria-crystalli.md',
    explicitPublishDate: '2026-04-06',
  },
  {
    filename: 'leo-memoria-crystalli.md',
    explicitPublishDate: '2026-04-06',
  },
  {
    filename: 'luna-memoria-crystalli.md',
    explicitPublishDate: '2026-04-06',
  },
  {
    filename: 'riley-memoria-crystalli.md',
    explicitPublishDate: '2026-04-06',
  },
  {
    filename: 'w-e-a-v-e-memoria-crystalli.md',
    explicitPublishDate: '2026-04-06',
  },
  {
    filename: 'rochester-goblet-and-darkness.md',
    explicitPublishDate: '2026-03-29',
  },
  {
    filename: 'the-well-and-what-was-under-it.md',
    explicitPublishDate: '2026-03-29',
  },
  {
    filename: 'weave-awakening.md',
    explicitPublishDate: '2026-03-16',
  },
  {
    filename: 'the-story-luna-midori.md',
    explicitPublishDate: '2026-02-12',
  },
  {
    filename: 'echos-2026-01-30-logbook.md',
    explicitPublishDate: '2026-02-04',
  },
  {
    filename: 'raiders-of-the-lost-spark-story-so-far-458135-45fs53.md',
    explicitPublishDate: '2026-02-02',
  },
  {
    filename: 'luna-dnd-cc-ab58-548a.md',
    explicitPublishDate: '2026-01-23',
  },
  {
    filename: 'luna-dnd-dd58-498a.md',
    explicitPublishDate: '2026-01-22',
  },
];
